export const CREATE_GAME = "CREATE_GAME";
export const INITIALIZE_ENCOUNTERS = "INITIALIZE_ENCOUNTERS";
export const RENDER_MINIGAME = "RENDER_MINIGAME";
export const RENDER_RESULTS = "RENDER_RESULTS";
export const RENDER_PROMPT = "RENDER_PROMPT";
export const RENDER_STORY = "RENDER_STORY";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const UPDATE_CHARACTER_STATS = "UPDATE_CHARACTER_STATS";